project_name: excelgrep
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: eg
    goos:
    - darwin
    - windows
    ldflags:
      - -s -w
      - -X github.com/momiom/excelgrep/cmd.Version={{.Version}}
      - -X github.com/momiom/excelgrep/cmd.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
